### ISSUE TITLE
Use trait object

### ISSUE THREAD

**Issue by Ericson2314** [multiformats/rust-multihash#2]
Same reasoning as https://github.com/multiformats/rust-multiaddr/issues/11

**Comment by Ericson2314** [comment]
Assume PR is good for this one too? Do you care about using unstable features? https://crates.io/crates/stack_dst/ is a clever way to make bounded trait objects to avoid allocations. I'd use this with a size big enough to accommodate the largest multihash in existance today. Unfortunately because it uses the `Unsize` magic trait, it requires unstable.

**Comment by dignifiedquire** [comment]
> Assume PR is good for this one too?

yep same answer as in rust-multiaddr :)

> Do you care about using unstable features?

I like to avoid them if possible to make it as easy as possible for everyone to use it, but if the reason is good enough I'm fine with using them. 

> https://crates.io/crates/stack_dst/ 

This does look pretty neat, so I think I'm using it. If you do a PR though, could you please make sure to put a link to the instructions on how to use unstable features into the readme?

**Comment by Ericson2314** [comment]
@dignifiedquire now that I think more about it, it should be possible to make this an optional feature and always expose plain-old `Box<Multihash>`. Then everybody wins!

**Comment by dignifiedquire** [comment]
Sweet, that sounds great :)

**Comment by briansmith** [comment]
I don't think this can be extensible because it requires a central registry of hash function IDs. If it were extensible then two trait implementations might use the same hash function ID for different purposes.

**Comment by dignifiedquire** [comment]
@briansmith what if the hash function list and the ids were extensible? Looking at the current implementation I'm unsure if the way I implemented HashTypes makes sense or not. Any input if there is a better rustful way to do it?

**Comment by Ericson2314** [comment]
@briansmith yeah ideally we'd use coherence and type-level nats, but then the instances would be orphans. So it's not real extensibility, but it's a step in the right direction.

IMO this is a fairly common issue with these "umbrella" formats, so I should open like an RFC issue for it---it would be nice to have a working example though before I write that however :).

**Comment by briansmith** [comment]
> What if the hash function list and the ids were extensible?

Presumably the data format is intended to be interoperable across implementations. That means there needs to be a 1-to-1 mapping between algorithms and IDs. The only way to maintain a 1-to-1 mapping is either a central registry of some sort, AFAICT.

**Comment by Ericson2314** [comment]
@briansmith Think it would be nice if *only* the central registry was centralized, and everything else could be modular. Ideally coherence would be my implicit central registry.

**Comment by maciejhirsz** [comment]
I think it would be easier to change `Hash` from enum to a trait, and store it internally as a static ref trait object:

```rust
pub struct Multihash<'a> {
    alg: &'static Algorithm,
    digest: &'a [u8],
}

pub trait Algorithm {
    fn code() -> u8;
    fn name() -> &'static str;
    fn encode(&[u8]) -> Vec<u8>;
}
```

The only problem here is that there needs to be a global list of all Algorithms, so you can register custom `Algorithm` implementations in Multihash. This could be done by using `lazy_static` to create a `RefCell<Vec<&'static Algorithm>>`, or even `RefCell<[&'static Algorithm, 256]>` if we sort them out by code.

**Comment by chpio** [comment]
im working on this right now:
https://ipfs.io/ipfs/QmbBivUVE9YjMk91wqEL4aN3jrSBczyiTt3eaENVER36ii/mf_multihash/


the structure in few words:
* there is a wrapper type for the hash and the algorithm (*Multihash* & *Algo*)
  * they are "real" structs
  * they are implementing necessary stuff like the *Eq* & *Hash* traits
* then there are the inner traits (*InnerMultihash* & *InnerAlgo*)
  * they are trait objects, what makes some traits unimplementable on them (*Eq* & *Hash*)
* there is a *Registry* struct
  * it's mapping codes to algos and the other way around
  * it's doing the serializations and deserializations
  * implements *Default* (returns a filled registry)


if you want to do customizations:
* you can change the mapping of codes => algos in the registry
* if you want to implement your own Algo you need to:
  * implement *InnerAlgo* & *InnerMultihash*
  * make a [static variable of your *InnerAlgo*](https://ipfs.io/ipfs/QmbBivUVE9YjMk91wqEL4aN3jrSBczyiTt3eaENVER36ii/mf_multihash/hashes/static.SHA1.html)
  * register the *Algo* on the registry

upsides:
* multihashes are usable in structs (the `&'a [u8]` ref makes the original impl pretty useless)
* it's implementing *Hash* & *Eq*, they are necessary if you want to use a multihash as a key in an *HashMap*


downsides:
* increased runtime overhead (dynamic dispatching because of trait objects)
* heap allocations (Box) of *InnerMultihash*

**Comment by rklaehn** [comment]
I guess this can be closed, since it is similar to what has been merged in the big refactor...

**Comment by vmx** [comment]
This issue got solved with https://github.com/multiformats/rust-multihash/pull/60 you can now have your own code table, hence can extend things and you don't rely on a closed enum.
