### ISSUE TITLE
Should be a trait

### ISSUE THREAD

**Issue by dvc94ch** [multiformats/rust-multihash#64]
This is really all we care about for libipld currently, but we cant do `H::digest()` or `H::CODE` on a type that implements `MultihashDigest`.

```rust
impl $name {
    #[doc = $code_doc]
    pub const CODE: Code = Code::$name;
    /// Hash some input and return the Multihash digest.
    pub fn digest(data: &[u8]) -> Multihash {
        let digest = <$type>::digest(&data);
        wrap(Self::CODE, &digest)
    }
}
```

**Comment by vmx** [comment]
Thanks for the suggestion. I agree that the current API is not as nice as it could be. Though there is a reason why the `MultihashDigest` is what it is today. I deliberately decided (see https://github.com/multiformats/rust-multihash/pull/63#issuecomment-607931425 for more information) that I don't want to introduce another trait. I want to have a trait that also works for trait objects. The [`digest` crate](https://docs.rs/digest/0.8.1/digest/index.html) has two different traits (`Digest` and `DigestDyn`) for that reason. I wanted to get away with only a single one. I prefer APIs where there's only one way of doing things.

Hence I suggest that for libipld, we use the `MultihashDigest` for now and if it turns out to be used a lot and hence it's unergonomic or if it becomes a performance bottleneck, we can still introduce it then.

**Comment by dvc94ch** [comment]
but libp2p actually uses it in the same way, so it's costing both libipld and libp2p a heap allocation, for no reason

**Comment by vmx** [comment]
IIRC, the usage in libp2p needs it to be a trait object. But I'll check again tomorrow.

**Comment by dvc94ch** [comment]
No it just requires a digest function on code. That can be implemented without boxing it first

**Comment by vmx** [comment]
Yes, it could be used without a trait. My idea was that custom code tables work with the whole ecosystem. This way every code table would also need to implement a `digest()` function. That might be OK for libp2p as it probably will never use a custom codec table. Though that's not true for IPLD.

**Comment by dvc94ch** [comment]
So what we need is a different trait, a Code trait that includes a digest function?

**Comment by dvc94ch** [comment]
In any case can you merge the cid pr and review the ipld pr? Then we can revisit the issue...
